// reasons.js (Create a separate file for better organization if necessary)
export const reasons = [
	"You always find a reason to smile in every situation.",
	"Your laughter, even from afar, brings my heart so much joy.",
	"You speak with both our moms every day.",
	"You care deeply for your brother and support him however you can.",
	"You regularly visit orphan homes to provide food and comfort.",
	"You donate all your clothes to charity.",
	"You keep both of us healthy and strong.",
	"You also like playing tennis.",
	"You also prefer comedies and nicer movies.",
	"You like watching documentaries together.",
	"You have a great sense of style.",
	"You have very cute little feet.",
	"You have beautiful green eyes that I can't stop gazing into.",
	"You have very soft skin.",
	"You are always clean and naturally smell very good.",
	"You do not use a ton of makeup.",
	"You do not use perfumes.",
	"You appreciate education and learning.",
	"You like using your time productively or creatively.",
	"You work out every day.",
	"You cook super healthy and tasty food.",
	"You are great with money and help us save every month.",
	"You are very educated and polite.",
	"You can leave a great impression in any social gathering.",
	"You allow yourself to laugh out loud often.",
	"You love and care for everyone in our family.",
	"You buy me amazing gifts every year.",
	"You sometimes pamper me with a relaxing massage at the end of a long day.",
	"You are forward-thinking.",
	"You are hard working.",
	"You invest a ton into your personal development.",
	"You are very coachable and learn fast.",
	"You give me feedback on how to be better.",
	"You motivate me to push harder and reach my goals.",
	"You are always attentive and caring.",
	"You are on my mind all day long.",
	"You also like cuddling, hugs, and kisses.",
	"You also like dogs.",
	"You like mainly the same styles of music.",
	"You appreciate classical music.",
	"You also like going to classical music concerts and theatre.",
	"You are always open to trying new things.",
	"You also love traveling.",
	"You make every one of our trips amazing.",
	"You are open to having important conversations.",
	"You seek feedback on how to improve.",
	"You work hard to keep your super hot small waist.",
	"You know how to be sexy.",
	"You are careful about what you say and do.",
	"You have empathy towards how others might feel.",
	"You have very enchanting, womanly hands and forearms.",
	"You are grateful every day for what we have.",
	"You appreciate the small things in life, like a pleasant walk or a great cup of tea.",
	"You keep our home clean and organized.",
	"You love me to the moon and back.",
	"You make me a better man, every day.",
	"You keep your nails short and cute.",
	"You also want to raise healthy children.",
	"You are open to practical forms of education.",
	"You also prefer we live in smaller cities.",
	"You coming with me on a trip gets me 10X more excited for it.",
	"You are resourceful.",
	"You are hard-working.",
	"You never complain.",
	"You don't point fingers.",
	"You don't talk badly of others.",
	"You can always see other people's point of view.",
	"You wrote your vision statement and you keep it updated.",
	"You created a vision board with me that we see everyday.",
	"You go out of your way to help others.",
	"You put in a ton of effort to help our parents and family.",
	"You buy me gifts that I actually love.",
	"You plan awesome trips.",
	"You write me beautiful letters every year.",
	"You show you're grateful for our lives every day.",
	"You think of ways to grow our relationship every month.",
	"You block time for our date night every week.",
	"You dress beautifully every time we go on a date.",
	"You are a life partner I can and do proudly speak of and present.",
	"You have a great sense of clothing.",
	"You keep your beautiful body free of piercings and tattoos.",
	"You have outstanding moral values.",
	"You respect all religions and beliefs.",
	"You respect people of all nations and races.",
	"You take time for yourself whenever you need it.",
	"You have dignity and stand your ground when appropriate.",
	"You prepare the most amazing nachos ever.",
	"You plan your week in advance so you focus on what matters most.",
	"You implemented every bit of feedback I ever gave you.",
	"You say please and thank you very often.",
	"You give me energy to get through very long work days.",
	"You block time for us to count our blessings together every week.",
	"You avoid processed sugar.",
	"You avoid bread and any meal that has flour.",
	"You like going to the gym with me.",
	"You always find reasons to smile and laugh.",
	"You trust me enough to tell me everything that's on your mind.",
	"You love saving money and investing just as much as I do.",
	"You do more work around the house than I could ever ask for.",
	"You keep finding affordable alternatives for the things we want.",
	"You are not scared of big projects we plan on doing.",
	"You leave the past in the past.",
	"You have the courage to face your demons and grow.",
	"You are always forward-thinking.",
	"You also love going on super long walks in nature.",
	"You make the most out of every situation.",
	"You understand the compromises we make and find ways to work around them.",
	"You love books and reading just as much as I do.",
	"You are open to hearing and accepting other people’s points of view.",
	"You listen to audiobooks whilst you cook or clean.",
	"You hug me and all my worries go away.",
	"You are also seriously considering adopting children.",
	"You make me feel like I can achieve anything.",
	"You sleep on my chest and all snuggled up around me.",
	"You also appreciate fruits and vegetables from our family.",
	"You like going to volunteer for charities and causes together.",
	"You prefer and wear only a small amount of jewelry.",
	"You give me inspiration when I need it most.",
	"You sleep very peacefully and don't make any sounds.",
	"You don't mind me waking up at weird hours to work.",
	"You give me space to work on all of my businesses.",
	"You always take care of me when I get sick.",
	"You are constantly doing research on healthy recipes.",
	"You never said no to expensive learning opportunities.",
	"You also like decorating the house for Christmas.",
	"You like watching Christmas movies.",
	"You look better and better every year.",
	"You are super committed to our relationship.",
	"You are loyal and I can trust you to go anywhere alone.",
	"You don't put yourself into dangerous situations.",
	"You drive very safely and help me do the same.",
	"You like involving me in everything you do, like picking furniture.",
	"You make even grocery shopping something I look forward to doing with you.",
	"You are comfortable to let go and cry when we're together.",
	"You are grateful for your past.",
	"You appreciate all the hard work your parents put into raising you.",
	"You love your parents deeply, no matter their flaws.",
	"You encourage me to spend more time with my family.",
	"You make me feel like I've already made it.",
	"You make it easier for me to dream big and not be scared.",
	"You give me courage to push through difficult moments.",
	"You are willing to put in the work to make your dreams come true.",
	"You are everything I ever wanted, and more.",
]

export const title = "143 Reasons Why I Love You"

export const openingText = [
	"My Dear Diana,",
	"Ever since we've met I think I've told you at least 1,000,000 times 'I love you' and on many of those occasions you humorously asked 'Why?'",
	"As you know, I sometimes played along and, over the years, I've probably given you a thousand reasons.",
	"However, for this year's Valentine's Day, I decided to put together a small list of 143 reasons, in no particular order.",
	"Enjoy.",
]

export const closingText = [
	"Of course, I have many more reasons and I think it's important to mention this list does not mean I will stop sharing them with you. Quite the contrary. My plan is to remind you of all of the reasons why I love you, every single day, for as long as I live.",
]

export const signatureText = ["Your biggest fan,", "Robert"]
